apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-application
  namespace: default
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: crossplane
    repoURL: https://github.com/majesticbeast/argo-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
