apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: teams
    repoURL: https://github.com/majesticbeast/argo-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
