apiVersion: v1
kind: Service
metadata:
  name: kuard-service
  namespace: kuard
spec:
  type: LoadBalancer
  selector:
    app: kuard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
